# bd79602518f1d9f7be70e40286464688725a26f3 encoding: utf-8
# @@ 1

########################### DO NOT MODIFY THIS FILE ###########################
#       This file was automatically generated by JRubyFX-fxmlloader on        #
# 2017-01-02 23:25:34 +0100 for /media/druzy/dock/programmation/ruby/competence/competence/lib/about_view.fxml
########################### DO NOT MODIFY THIS FILE ###########################

module JRubyFX
  module GeneratedAssets
    class AOT2272cd2b65e8a4b6103a4c1997fa51a6566e6344
      include JRubyFX
          def __build_via_jit(__local_fxml_controller, __local_namespace, __local_jruby_ext)
      __local_fx_id_setter = lambda do |name, __i|
        __local_namespace[name] = __i
        __local_fxml_controller.instance_variable_set(("@#{name}").to_sym, __i)
      end

build(Java::JavafxSceneLayout::BorderPane) do
 __local_jruby_ext[:on_root_set].call(self) if __local_jruby_ext[:on_root_set]
 setBottom(build(Java::JavafxSceneLayout::AnchorPane) do
  getChildren.add(build(Java::JavafxSceneControl::Button) do
   setId("exit_button")
   setLayoutX(518.0)
   setLayoutY(11.0)
   setMnemonicParsing(false)
   setText("Fermer")
   setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "exit_button_clicked"))
   Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 14.0)
   Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 14.0)
   Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 14.0)
  end)
  setPrefHeight(43.0)
  setPrefWidth(600.0)
  Java::JavafxSceneLayout::BorderPane.setAlignment(self, Java::javafx::geometry::Pos::CENTER)
 end)
 setCenter(build(Java::JavafxSceneLayout::HBox) do
  getChildren.add(build(Java::JavafxSceneLayout::AnchorPane) do
   getChildren.add(build(Java::JavafxSceneImage::ImageView) do
    setId("image_view")
    setFitHeight(150.0)
    setFitWidth(200.0)
    setLayoutX(14.0)
    setLayoutY(14.0)
    setPickOnBounds(true)
    setPreserveRatio(true)
    Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 14.0)
    Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 14.0)
    Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 14.0)
   end)
   setPrefHeight(200.0)
   setPrefWidth(200.0)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::AnchorPane) do
   getChildren.add(build(FxmlBuilderBuilder, {"id"=>"web_view", "layoutX"=>"158.0", "layoutY"=>"14.0", "prefHeight"=>"346.0", "prefWidth"=>"372.0"}, Java::JavafxSceneWeb::WebView) do
    Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 0.0)
    Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 0.0)
    Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 0.0)
    Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 0.0)
   end)
   setPrefHeight(200.0)
   setPrefWidth(200.0)
   Java::JavafxSceneLayout::HBox.setHgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
  end)
  setPrefHeight(100.0)
  setPrefWidth(200.0)
  Java::JavafxSceneLayout::BorderPane.setAlignment(self, Java::javafx::geometry::Pos::CENTER)
 end)
 setMaxHeight(-Infinity)
 setMaxWidth(-Infinity)
 setMinHeight(-Infinity)
 setMinWidth(-Infinity)
 setPrefHeight(400.0)
 setPrefWidth(600.0)
end
    end

      def hash
        "bd79602518f1d9f7be70e40286464688725a26f3"
      end
      def compiled?
        true
      end
    end
  end
end
